### ISSUE TITLE
Picture broken on the about me page

### ISSUE THREAD

**Issue by marshallgallatin** [DarkManiel/DarkManiel.github.io#1]
FYI, your image is broken on the about me page:
http://darkmaniel.github.io/about/

thought you'd like to know 
(I'm another student in Downing's CS 371p class, not a stalker)

**Comment by DarkManiel** [comment]
Thanks for the heads up. I think it's fixed now. Just because you're another student in Downing's class doesn't mean you're not a stalker. :+1:
